import type { Crowd } from "./schema";

export type PlanGroup = "area" | "interest";

export type Plan = {
  id: string;
  title: string;
  blurb: string;
  group: PlanGroup;
  /** The filter chip this plan sits under, e.g. "North Kolkata" or "Date night". */
  tag: string;
  /** When to go. */
  best: string;
  crowd: Crowd;
  /** How to get around, in one line. */
  getting: string;
  /** Place slugs in visiting order (a baris/pandals/food mix). */
  stops: string[];
};

export const AREA_TAGS = ["North Kolkata", "Central Kolkata", "South Kolkata", "Salt Lake"] as const;
export const INTEREST_TAGS = [
  "Bonedi Baris",
  "Picturesque",
  "Less crowded",
  "Date night",
  "Foodie",
  "Family",
  "Late night",
  "Big themes",
] as const;

export const PLANS: Plan[] = [
  // ───────────────────────────── By area ─────────────────────────────
  {
    id: "north-shobhabazar-rajbari",
    group: "area",
    tag: "North Kolkata",
    title: "Shobhabazar Rajbaris & Darjipara",
    blurb: "The two Deb Rajbaris and their thakur dalan, then the nearby Mitra and Chatu Babu Latu Babu houses. Sweets mid-way, a Bengali meal at the end.",
    best: "Late morning to early evening",
    crowd: "high",
    getting: "Shobhabazar Sutanuti metro, then entirely on foot.",
    stops: [
      "shobhabazar-rajbari-radha-kanta-dev-estate",
      "shobhabazar-rajbari-thakur-dalan",
      "shobhabazar-rajbari-maharaja-naba-krishna-dev-bari",
      "nobin-chandra-das",
      "darjipara-mitra-bari",
      "chatu-babu-latu-babu-bari",
      "mitra-cafe",
    ],
  },
  {
    id: "north-girish-park-jorasanko",
    group: "area",
    tag: "North Kolkata",
    title: "Girish Park, Jorasanko & Pathuriaghata Baris",
    blurb: "Nine family houses in the old northern lanes. Finish at Pathuriaghata for the evening dhunuchi nach, best on Saptami.",
    best: "From 3 pm, so you reach Pathuriaghata before 7",
    crowd: "medium",
    getting: "Girish Park metro, then on foot. Use an auto for the last hop to Hatkhola.",
    stops: [
      "shamul-dhone-dutta-bari",
      "lala-bari",
      "daw-bari-bandook-wala",
      "shib-krishna-daw-bari",
      "harakutir-ray-banerjee-bari",
      "pathuriaghata-rajbari",
      "hathkhola-dutta-bari",
    ],
  },
  {
    id: "north-kumartuli-baghbazar",
    group: "area",
    tag: "North Kolkata",
    title: "Kumartuli, Baghbazar & Ahiritola",
    blurb: "The idol-makers' quarter and the classic North Kolkata sarbojanin pandals, with rasogolla history to finish.",
    best: "Late afternoon until about 9 pm",
    crowd: "high",
    getting: "Shobhabazar Sutanuti or Shyambazar metro, on foot between stops.",
    stops: [
      "kumartuli-sarbojanin",
      "baghbazar-sarbojanin",
      "baghbazar-haldar-bari",
      "nobin-chandra-das",
      "kumartuli-park",
      "ahritola-sarbojanin",
      "kashi-bose-lane",
      "girish-chandra-dey-nakur-chandra-nandy",
    ],
  },
  {
    id: "north-hatibagan-maniktala",
    group: "area",
    tag: "North Kolkata",
    title: "Hatibagan, Maniktala & Shyambazar",
    blurb: "Award-winning Chaltabagan pandals, two Maniktala houses, the Lalabagan pandal and a Shyambazar sweets-and-kosha-mangsho finish.",
    best: "Early evening, then dinner at Shyambazar",
    crowd: "high",
    getting: "Girish Park or Shyambazar metro. Autos between Maniktala stops.",
    stops: [
      "hatibagan-sarbojanin",
      "bholanath-dham-dutta-bari",
      "maniktala-saha-bari",
      "maniktala-chaltabagan",
      "chaltabagan-lohapatty",
      "lalabagan-nabankur",
      "adi-haridas-modak",
      "golbari",
    ],
  },
  {
    id: "north-far-north",
    group: "area",
    tag: "North Kolkata",
    title: "Far North: Tala, Dum Dum & Lake Town",
    blurb: "Tala Prattay, Dum Dum Park and the giant Shreebhumi set. Spread out, so go by cab, and plan Shreebhumi for late or early.",
    best: "Weekday evening, or after midnight for Shreebhumi",
    crowd: "extreme",
    getting: "Cab or app bike between stops. Belgachhia or Dum Dum metro help for the first two.",
    stops: ["tala-prattay", "dum-dum-park", "shreebhumi-sporting-club"],
  },
  {
    id: "central-college-street",
    group: "area",
    tag: "Central Kolkata",
    title: "College Street, Colootola & Chorbagan",
    blurb: "A walkable heritage loop: the Thanthania, Colootola and Chorbagan houses, College Square's lakeside pandal and coffee at the Indian Coffee House.",
    best: "Late morning to dusk",
    crowd: "medium",
    getting: "MG Road or Central metro, then walking.",
    stops: [
      "thantania-dutta-bari",
      "chorbagan-sarbojanin",
      "chorbagan-mitra-bari",
      "chorbagan-sil-bari",
      "badan-chand-roy-bari",
      "indian-coffee-house",
      "college-square",
      "ramgopal-saha-bari",
      "putiram",
      "dilkhusha-cabin",
    ],
  },
  {
    id: "central-esplanade-sealdah",
    group: "area",
    tag: "Central Kolkata",
    title: "Esplanade to Sealdah",
    blurb: "Chinatown noodles, Rani Rashmoni's Janbazar mansion, then the big Central pandals: Taltala, Mohammed Ali Park and Santosh Mitra Square.",
    best: "Early afternoon start. Do Santosh Mitra Square last or very late.",
    crowd: "extreme",
    getting: "Esplanade metro. Green Line to Sealdah for the end.",
    stops: [
      "eau-chew",
      "k-c-das",
      "rani-roshmoni-bari",
      "taltala-sarbojanin",
      "santosh-mitra-square",
      "nilmani-mitra-bari",
      "mohammed-ali-park",
    ],
  },
  {
    id: "south-kalighat",
    group: "area",
    tag: "South Kolkata",
    title: "Kalighat Pandal Circuit",
    blurb: "The pandals around Kalighat metro, from the 64, 66 and 68 Pallys to Mudiali, Tridhara and Deshapriya Park, with coffee at the end.",
    best: "Weekday evenings. Deshapriya Park is crowded after 8 pm.",
    crowd: "extreme",
    getting: "Kalighat metro, then walking and short autos.",
    stops: [
      "kalighat-milan-sangha",
      "68-pally",
      "64-pally",
      "66-pally",
      "badamtala-ashar-sangha",
      "chetla-agrani",
      "mudiali-club",
      "deshapriya-park",
      "tridhara-sammilani",
      "c-lab-coffee-calcutta-deshapriya-park",
    ],
  },
  {
    id: "south-ballygunge-gariahat",
    group: "area",
    tag: "South Kolkata",
    title: "Ballygunge & Gariahat Pandals",
    blurb: "Ballygunge Cultural, Singhi Park, Maddox Square, Hindustan Park, Dover Lane and Ekdalia Evergreen, with coffee and dinner right on the route.",
    best: "From 5 pm. Maddox Square is lively until very late.",
    crowd: "extreme",
    getting: "Jatin Das Park metro and walking; autos between Ekdalia and Hindustan Park.",
    stops: [
      "craft-coffee-experience-centre-ballygunge",
      "ekdalia-evergreen",
      "singhi-park",
      "dover-lane",
      "sienna",
      "hindustan-park",
      "ballygunge-cultural-association",
      "maddox-square",
    ],
  },
  {
    id: "south-jadavpur-naktala",
    group: "area",
    tag: "South Kolkata",
    title: "Jadavpur & Naktala",
    blurb: "Suruchi Sangha, the Jadavpur 8B and Aikatan pandals, and Naktala Udayan Sangha, with a coffee stop at Lake Gardens.",
    best: "Early evening on a weekday",
    crowd: "high",
    getting: "Cab or auto between stops. Kavi Subhash metro is the nearest end.",
    stops: [
      "colab-coffee-calcutta",
      "aikatan",
      "jadavpur-8b",
      "naktala-udayan-sangha",
      "suruchi-sangha",
    ],
  },
  {
    id: "south-alipore-bhowanipore",
    group: "area",
    tag: "South Kolkata",
    title: "Alipore & Bhowanipore",
    blurb: "A calm leafy loop: the three Alipore pandals, the Mallick Bari at Bhowanipore, and a Bengali dinner.",
    best: "Late afternoon to dinner",
    crowd: "medium",
    getting: "Cab. Netaji Bhavan metro is closest to Bhowanipore.",
    stops: [
      "alipore-78-pally",
      "netaji-sangha",
      "alipore-sarbojanin",
      "deshbandhu-park",
      "mallick-bari",
      "yours-truly-coffee-roaster",
      "kewpie-s-kitchen",
    ],
  },
  {
    id: "south-kasba",
    group: "area",
    tag: "South Kolkata",
    title: "Kasba & Bosepukur",
    blurb: "The quieter Kasba pandals: 14 Pally, Natun Dal, Udichi and Bosepukur Sitala Mandir.",
    best: "Any evening. It is rarely packed.",
    crowd: "low",
    getting: "Cab or auto. These four are close together.",
    stops: ["kasba-14-pally", "natun-dal", "udichi", "bosepukur-sitala-mandir"],
  },
  {
    id: "south-behala-baris",
    group: "area",
    tag: "South Kolkata",
    title: "Behala: The Oldest Puja",
    blurb: "The Sabarna Roy Choudhury Atchala Bari at Barisha (from 1610) and the Roy house in Behala. A half-day trip on its own.",
    best: "Daytime",
    crowd: "medium",
    getting: "Cab, or Purple Line to Behala Chowrasta then an auto.",
    stops: ["sabarna-roy-chowdhury-atchala-bari", "amarendra-bhavan-roy-bari"],
  },
  {
    id: "saltlake-sector-1",
    group: "area",
    tag: "Salt Lake",
    title: "Salt Lake: Sector 1 Blocks",
    blurb: "AE, AB, BJ, CE and AK blocks, then dinner at City Centre. Roads are wide and it is easy to go by cab.",
    best: "Early evening",
    crowd: "medium",
    getting: "Cab or app bike between blocks. Salt Lake Stadium metro for the start.",
    stops: [
      "25-main-street-cafe",
      "kaafila",
      "sonar-tori",
      "ce-block",
      "ae-block",
      "bj-block",
      "ak-block",
      "ab-block",
    ],
  },
  {
    id: "saltlake-sector-3",
    group: "area",
    tag: "Salt Lake",
    title: "Salt Lake: Sector 3 & FD Block",
    blurb: "FD Block's big set, plus FE, GD, IB and Laboni Estate, with coffee beside FD Block.",
    best: "Weekday evening, or late night for FD Block",
    crowd: "high",
    getting: "Cab or app bike between blocks.",
    stops: [
      "craft-coffee-experience-centre-salt-lake",
      "fd-block",
      "fe-block",
      "gd-block",
      "ib-block",
      "laboni-estate",
    ],
  },

  // ───────────────────────────── By interest ─────────────────────────────
  {
    id: "bari-big-names",
    group: "interest",
    tag: "Bonedi Baris",
    title: "Bonedi Baris: The Big Names",
    blurb: "The most famous family Pujas across North and Central Kolkata, from Shobhabazar and Jorasanko to Colootola and Rani Rashmoni's Janbazar.",
    best: "Daytime, and Pathuriaghata at 7 pm",
    crowd: "high",
    getting: "Cab hops between areas, with walking inside each cluster.",
    stops: [
      "shobhabazar-rajbari-radha-kanta-dev-estate",
      "shobhabazar-rajbari-maharaja-naba-krishna-dev-bari",
      "chatu-babu-latu-babu-bari",
      "pathuriaghata-rajbari",
      "shib-krishna-daw-bari",
      "badan-chand-roy-bari",
      "rani-roshmoni-bari",
    ],
  },
  {
    id: "bari-quiet-houses",
    group: "interest",
    tag: "Bonedi Baris",
    title: "Bonedi Baris: Quiet Old Houses",
    blurb: "The lesser-visited family Pujas: Chorbagan, Thanthania, Ramgopal Saha, Shamul Dhone Dutta, Harakutir, Hatkhola, Maniktala and Bholanath Dham.",
    best: "Afternoons and early evenings",
    crowd: "low",
    getting: "Cab hops, then walking.",
    stops: [
      "thantania-dutta-bari",
      "maniktala-saha-bari",
      "bholanath-dham-dutta-bari",
      "shamul-dhone-dutta-bari",
      "hathkhola-dutta-bari",
      "harakutir-ray-banerjee-bari",
      "chorbagan-sil-bari",
      "chorbagan-mitra-bari",
      "ramgopal-saha-bari",
    ],
  },
  {
    id: "bari-south",
    group: "interest",
    tag: "Bonedi Baris",
    title: "Bonedi Baris of the South",
    blurb: "The Mallick Bari at Bhowanipore, then south to the Roy Choudhury Atchala Puja and the Roy house at Behala.",
    best: "Daytime",
    crowd: "medium",
    getting: "Cab for the Behala leg.",
    stops: [
      "mallick-bari",
      "kewpie-s-kitchen",
      "amarendra-bhavan-roy-bari",
      "sabarna-roy-chowdhury-atchala-bari",
    ],
  },
  {
    id: "picturesque-pandals",
    group: "interest",
    tag: "Picturesque",
    title: "Picturesque Pandal Hopping",
    blurb: "The pandals best known for lights, scale and setting, from College Square's lake to Maddox Square's glow.",
    best: "Dusk, when the lights switch on, then late night",
    crowd: "extreme",
    getting: "Metro to Central, then cab to the south. Walk between south stops.",
    stops: [
      "college-square",
      "mohammed-ali-park",
      "santosh-mitra-square",
      "maddox-square",
      "singhi-park",
      "ekdalia-evergreen",
      "hindustan-park",
      "tridhara-sammilani",
      "deshapriya-park",
      "mudiali-club",
    ],
  },
  {
    id: "less-crowded-south",
    group: "interest",
    tag: "Less crowded",
    title: "Less Crowded: Alipore to Kasba",
    blurb: "Calm neighbourhood pandals in Alipore, Kasba and Jadavpur, where you can actually look at the idol.",
    best: "Any evening, including weekends",
    crowd: "low",
    getting: "Cab between the three clusters.",
    stops: [
      "alipore-78-pally",
      "68-pally",
      "deshbandhu-park",
      "alipore-sarbojanin",
      "netaji-sangha",
      "jadavpur-8b",
      "aikatan",
      "kasba-14-pally",
      "natun-dal",
      "udichi",
    ],
  },
  {
    id: "less-crowded-north",
    group: "interest",
    tag: "Less crowded",
    title: "Less Crowded: North & Central Lanes",
    blurb: "Smaller pandals and quiet houses where the lanes stay passable: Kashi Bose Lane, Lalabagan, Ahiritola, Taltala and Chorbagan.",
    best: "Early evening",
    crowd: "low",
    getting: "Cab or autos, with walking between nearby stops.",
    stops: [
      "chorbagan-sarbojanin",
      "hathkhola-dutta-bari",
      "ahritola-sarbojanin",
      "baghbazar-haldar-bari",
      "kashi-bose-lane",
      "lalabagan-nabankur",
      "taltala-sarbojanin",
    ],
  },
  {
    id: "date-south",
    group: "interest",
    tag: "Date night",
    title: "Date Night: Gariahat & Lake Market",
    blurb: "Coffee, three of the prettiest pandals, then a proper dinner and dessert, all within a short walk.",
    best: "From 5 pm. Book dinner ahead.",
    crowd: "high",
    getting: "Jatin Das Park metro or a cab, then walking.",
    stops: [
      "rever-glasshouse-cafe",
      "ballygunge-cultural-association",
      "bonne-femme",
      "hindustan-park",
      "dulcie-dubai",
      "dover-lane",
      "maddox-square",
    ],
  },
  {
    id: "date-central",
    group: "interest",
    tag: "Date night",
    title: "Date Night: College Square to Park Street",
    blurb: "A lakeside pandal, a heritage mansion and a Park Street dinner and drinks.",
    best: "Late afternoon into the night",
    crowd: "high",
    getting: "Central or MG Road metro, then Esplanade and Park Street by metro or cab.",
    stops: [
      "indian-coffee-house",
      "college-square",
      "rani-roshmoni-bari",
      "olterra",
      "glenburn-cafe",
      "sorano",
      "cobo-calcutta",
    ],
  },
  {
    id: "foodie-park-street",
    group: "interest",
    tag: "Foodie",
    title: "Foodie & Drinks: Park Street Strip",
    blurb: "Heritage dining at Kwality and Mocambo, then the cafe-bar and brewery crowd, all within a few hundred metres.",
    best: "Evening, any day (book Mocambo ahead on Puja weekends)",
    crowd: "high",
    getting: "Park Street or Esplanade metro, then entirely on foot.",
    stops: [
      "kwality-park-street",
      "park-street-social",
      "someplace-else",
      "mocambo",
      "olterra",
      "ampm-park-street",
    ],
  },
  {
    id: "foodie-mishti-trail",
    group: "interest",
    tag: "Foodie",
    title: "Foodie: Mishti Trail",
    blurb: "Four of Kolkata's best-rated sweet shops, from Bagbazar to Bowbazar, College Street and Bhowanipore. Cab hops between them.",
    best: "Daytime, when everything is fresh",
    crowd: "medium",
    getting: "Cab or auto between shops; Girish Park, Central and Kalighat metro each reach one.",
    stops: [
      "girish-chandra-dey-nakur-chandra-nandy",
      "putiram",
      "bhim-chandra-nag",
      "balaram-mullick-radharaman-mullick",
    ],
  },
  {
    id: "foodie-old-kolkata",
    group: "interest",
    tag: "Foodie",
    title: "Foodie: Old North Kolkata",
    blurb: "Shyambazar's century-old eateries, Bengal's sweet shops and a couple of North Kolkata pandals.",
    best: "From 4 pm",
    crowd: "high",
    getting: "Shyambazar metro, then on foot or by auto.",
    stops: [
      "adi-haridas-modak",
      "golbari",
      "rupa-hotel",
      "sen-mahasay",
      "hatibagan-sarbojanin",
      "allen-kitchen",
      "nobin-chandra-das",
      "mitra-cafe",
      "kumartuli-park",
      "ahritola-sarbojanin",
      "girish-chandra-dey-nakur-chandra-nandy",
    ],
  },
  {
    id: "foodie-south",
    group: "interest",
    tag: "Foodie",
    title: "Foodie: Hindustan Park Crawl",
    blurb: "A Bengali lunch, cafes and pandals around Hindustan Park, ending with something sweet.",
    best: "Lunch to late evening",
    crowd: "high",
    getting: "Jatin Das Park metro, then walking.",
    stops: [
      "restaurant-at-amar-khamar",
      "bonne-femme",
      "sienna",
      "hindustan-park",
      "dulcie-dubai",
      "dover-lane",
      "maddox-square",
    ],
  },
  {
    id: "family-easy",
    group: "interest",
    tag: "Family",
    title: "Family & Elders: Short and Seated",
    blurb: "Few stops, little walking and a proper sit-down meal. The Mallick Bari, two calm Alipore pandals and a family restaurant.",
    best: "Late afternoon to early evening",
    crowd: "medium",
    getting: "Cab door to door. No long walks.",
    stops: ["mallick-bari", "alipore-78-pally", "deshbandhu-park", "kewpie-s-kitchen"],
  },
  {
    id: "late-night-south",
    group: "interest",
    tag: "Late night",
    title: "Night Owls: After 11 pm",
    blurb: "When the crowds thin, from Maddox Square's all-night energy to the 24-hour Balwant Singh dhaba for chai.",
    best: "11 pm onwards",
    crowd: "medium",
    getting: "Cab or app bike. Check whether the metro is running late.",
    stops: [
      "maddox-square",
      "deshapriya-park",
      "hindustan-park",
      "ekdalia-evergreen",
      "balwant-singh-dhaba",
    ],
  },
  {
    id: "themes-south",
    group: "interest",
    tag: "Big themes",
    title: "Big-Theme Showdown: South",
    blurb: "The big, ambitious South Kolkata sets in one run: Deshapriya Park, Singhi Park, Ekdalia, Suruchi Sangha and more.",
    best: "Weekdays, early evening or after midnight",
    crowd: "extreme",
    getting: "Cab or app bike between clusters.",
    stops: [
      "badamtala-ashar-sangha",
      "chetla-agrani",
      "suruchi-sangha",
      "mudiali-club",
      "deshapriya-park",
      "tridhara-sammilani",
      "singhi-park",
      "ekdalia-evergreen",
      "naktala-udayan-sangha",
    ],
  },
];

export const planById = new Map(PLANS.map((p) => [p.id, p]));

/** A suggested way to spend each day of the festival (2026 dates: Shashthi 17 Oct to Dashami 21 Oct). */
export const PUJA_DAYS: { day: string; date: string; theme: string; plans: string[]; note: string }[] = [
  {
    day: "Shashthi",
    date: "Sat 17 Oct",
    theme: "A gentle start",
    plans: ["north-kumartuli-baghbazar"],
    note: "Idol lanes and the classic sarbojanin pandals. Calm compared with the days ahead.",
  },
  {
    day: "Saptami",
    date: "Sun 18 Oct",
    theme: "The grand houses",
    plans: ["bari-big-names", "north-girish-park-jorasanko"],
    note: "Bonedi Baris by day, Pathuriaghata's dhunuchi nach around 7 pm.",
  },
  {
    day: "Ashtami",
    date: "Mon 19 Oct",
    theme: "Quiet houses by day, big themes by night",
    plans: ["bari-quiet-houses", "themes-south"],
    note: "Check the panjika for Sandhi Puja timing. The big pandals are heaviest tonight, so arrive early or very late.",
  },
  {
    day: "Navami",
    date: "Tue 20 Oct",
    theme: "Central and Salt Lake",
    plans: ["central-esplanade-sealdah", "saltlake-sector-3"],
    note: "Santosh Mitra Square late, Salt Lake blocks by cab.",
  },
  {
    day: "Dashami",
    date: "Wed 21 Oct",
    theme: "Farewell and sweets",
    plans: ["less-crowded-north", "date-central"],
    note: "Quiet houses in the day. Expect road restrictions near the Ganga ghats for immersion processions.",
  },
];
